-- ==============================================
-- TB_REGION, TB_THEME 시드 데이터
-- (DDL의 SEQ_REGION, SEQ_THEME 사용 · TB_REGION/TB_THEME 구조 기준)
-- 테이블 생성 및 시퀀스 생성 후 실행. 이미 행이 있으면 중복 키 오류 가능.
-- ==============================================

-- TB_REGION (지역) — REGION_NO: SEQ_REGION.NEXTVAL
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'서울');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'인천');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'경기');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'세종');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'강원도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'제주도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'충청남도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'충청북도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'전라남도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'전라북도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'경상남도');
INSERT INTO TB_REGION (REGION_NO, REGION_NAME) VALUES (SEQ_REGION.NEXTVAL, N'경상북도');

-- TB_THEME (테마) — THEME_NO: SEQ_THEME.NEXTVAL
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'호캉스');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'전통 문화');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'액티비티');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'자연/풍경');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'바다/해변');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'캠핑/차박');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'전시/공연');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'계절 꽃놀이');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'식도락/맛집');
INSERT INTO TB_THEME (THEME_NO, THEME_NAME) VALUES (SEQ_THEME.NEXTVAL, N'기타');

COMMIT;
